In [5]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import time
import random
from tqdm import tqdm
import psycopg2
from newsapi import NewsApiClient
from datetime import datetime, timedelta

In [6]:
from config import api_key, host, username, password

## News API

In [8]:
# instantiate newsapi object
newsapi = NewsApiClient(api_key='f418175c97314f91ad85efb39a9b1948')

# instantiate dataframe
df = pd.DataFrame()

# instantitate list with tickers
search_terms = ['TSLA', 'Tesla', 'Elon Musk']

# loop through all tickers
for search_term in search_terms:
    
    # get articles from first 5 pages - News API limit for Free Tier
    for page in tqdm(range(1, 6)):
        
        # request information
        all_articles = newsapi.get_everything(q=search_term, # search_term
                                              from_param=str(datetime.today()-timedelta(1))[:10], # yesterday
                                              to=str(datetime.today())[:10], # today
                                              language='en', # english
                                              page=page) # for 5 pages - Limit

        # create dataframe with information
        i_df = pd.DataFrame(all_articles['articles'])
        
        # add ticker column
        i_df['search_term'] = search_term

        # concatenate dataframes for all pages
        df = pd.concat([df, i_df], axis=0)

# reset dataframe's index
df = df.reset_index(drop=True)

# format source column to string
df['source'] = df['source'].map(lambda x: x['name'])

100%|██████████| 5/5 [00:01<00:00,  4.53it/s]
100%|██████████| 5/5 [00:02<00:00,  1.98it/s]
100%|██████████| 5/5 [00:01<00:00,  2.94it/s]

In [9]:
df

,source,author,title,description,url,urlToImage,publishedAt,content,search_term
0,Business Insider,Graham Rapier,There's one segment of electric vehicles even ...,<ul>\n<li>Electric cargo vans lie at the inter...,https://www.businessinsider.com/electric-deliv...,https://i.insider.com/5edaa66c3f73701be3147125...,2020-06-07T11:35:00Z,"Move over trucks and crossover SUVs, there's a...",TSLA
1,Yahoo Entertainment,Nelson Hem,"Bulls And Bears Of The Week: Gilead, Shopify, ...",* Benzinga has examined the prospects for many...,https://finance.yahoo.com/news/bulls-bears-wee...,https://s.yimg.com/uu/api/res/1.2/84mwN3L3qtL3...,2020-06-06T18:26:17Z,<ul><li>Benzinga has examined the prospects fo...,TSLA
2,Forbes,"Rob Isbitts, Senior Contributor, Rob Isbitts, ...",How Baby Boomers Should Handle A Tech-Dominate...,"We Baby Boomers emerged with cars, diesel engi...",https://www.forbes.com/sites/robisbitts2/2020/...,https://thumbor.forbes.com/thumbor/fit-in/1200...,2020-06-07T13:00:00Z,This image was taken by Matt H. Wade@thatmattw...,TSLA
3,Forbes,"Rahul Razdan, Contributor, Rahul Razdan, Contr...","Temple Grandin, Elon Musk, And The Interesting...",There is a surprising amount of commonality be...,https://www.forbes.com/sites/rahulrazdan/2020/...,https://thumbor.forbes.com/thumbor/fit-in/1200...,2020-06-07T14:12:03Z,Temple Grandin\r\nDenver Post via Getty Images...,TSLA
4,Yahoo Entertainment,Valuewalk,Rationalizing Tesla’s Stock Price,"On Monday, June 1, 2020, Tesla Inc. (NASDAQ:TS...",https://finance.yahoo.com/news/rationalizing-t...,https://s.yimg.com/uu/api/res/1.2/yGo4riR7hatJ...,2020-06-07T10:55:05Z,"On Monday, June 1, 2020, Tesla Inc. (NASDAQ:TS...",TSLA
...,...,...,...,...,...,...,...,...,...
178,Tutsplus.com,Alexis (Lexi) Rodrigo,25 Business Inspirational Quotes (for 2020) to...,Running a business is challenging even in the ...,https://business.tutsplus.com/articles/busines...,https://cms-assets.tutsplus.com/uploads/users/...,2020-06-06T12:55:26Z,Running a business is challenging even in the ...,Elon Musk
179,Somerset Live,Stephen D'Albiac,"COVID-19, Tesla in Somerset and lockdown chang...","COVID-19, Tesla in Somerset and lockdown chang...",https://www.somersetlive.co.uk/news/somerset-n...,https://i2-prod.somersetlive.co.uk/incoming/ar...,2020-06-07T20:19:47Z,These are unprecedented times; but even by the...,Elon Musk
180,fox5sandiego.com,"Marcia Dunn, AP Aerospace Writer","SpaceX opens era of amateur astronauts, cosmic...","Amateur astronauts, private space stations, fl...",https://fox5sandiego.com/news/tech/spacex-open...,https://fox5sandiego.com/wp-content/uploads/si...,2020-06-06T23:04:13Z,"CAPE CANAVERAL, Fla. (AP) SpaceXs debut astron...",Elon Musk
181,WSOC Charlotte,By MARCIA DUNN,"SpaceX opens era of amateur astronauts, cosmic...",SpaceX's debut astronaut launch is the biggest...,https://www.wsoctv.com/news/spacex-opens-era/V...,https://www.wsoctv.com/pb/resources/images/sha...,2020-06-06T13:20:29Z,"CAPE CANAVERAL, Fla. — (AP) SpaceXs debut astr...",Elon Musk
182,WUSA9.com,Associated Press,"SpaceX opens era of amateur astronauts, cosmic...","A week ago, SpaceX became the first private co...",https://www.wusa9.com/article/news/nation-worl...,https://media.wcnc.com/assets/CCT/images/804e4...,2020-06-06T15:56:48Z,SpaceX's debut astronaut launch is the biggest...,Elon Musk

In [ ]:
# connect to database
conn = psycopg2.connect(host='192.168.0.112',
                        user='gpp',
                        password='gppfp2123',
                        dbname='news')

# loop through all rows of the dataframe
for i in tqdm(df.index):

    # connect cursor
    with conn.cursor() as cur:

        # SQL query
        query = f'''
         
         INSERT INTO news_api 
         (source, author, title, description, url, urltoimage, published_at, content, ticker) 
         VALUES 
         ($${df['source'][i]}$$, $${df['author'][i]}$$,
         $${df['title'][i]}$$, $${df['description'][i]}$$,
         $${df['url'][i]}$$, $${df['urlToImage'][i]}$$,
         $${df['publishedAt'][i]}$$, $${df['content'][i]}$$,
         $${df['ticker'][i]}$$)
        
        '''

        # execute query
        cur.execute(query)

        # commit to modify database
        conn.commit()
        
print(f'{df.shape[0]} Rows Written to the Database!')

---

## Google NEWS API

In [ ]:
# move api_key, host_ip, username, password to config.py file

In [ ]:
api_key = 'a7cbd48203b116333d7959d7eb91c45c'

In [ ]:
search_term = 'TSLA'

In [ ]:
mindate = '2020-06-01'
maxdate = '2020-06-02'

In [ ]:
url = 'https://gnews.io/api/v3/search?q=' \
+ search_term \
+ '&mindate=' + mindate \
+ '&maxdate=' + maxdate \
+ '&token=' + api_key
res = requests.get(url)

In [ ]:
res.json()['articles'][0]

In [ ]:
google_df = pd.DataFrame(res.json()['articles'])

In [ ]:
google_df['source'] = google_df['source'].map(lambda x: x['name'])

In [ ]:
google_df['url'][0]

In [ ]:
# connect to database
conn = psycopg2.connect(host='192.168.0.112',
                        user='gpp',
                        password='gppfp2123',
                        dbname='news')

# loop through all rows of the dataframe
for i in tqdm(df.index):

    # connect cursor
    with conn.cursor() as cur:

        # SQL query
        query = f"INSERT INTO google_news (title, description, url, image, published_at, content, ticker) VALUES ($${df['source'][i]}$$, $${df['author'][i]}$$, $${df['title'][i]}$$, $${df['description'][i]}$$, $${df['url'][i]}$$, $${df['urlToImage'][i]}$$, $${df['publishedAt'][i]}$$, $${df['content'][i]}$$, $${df['ticker'][i]}$$)"

        # execute query
        cur.execute(query)

        # commit to modify database
        conn.commit()
        
print(f'{df.shape[0]} Rows Written to the Database!')

## Seeking Alpha
---

In [ ]:
user_agents = pd.read_csv('./user_agents.csv', header=None)
user_agents

In [ ]:
user_agents = user_agents.sample(2001, replace=True).values.tolist()

In [ ]:
user_agents[1][0]

In [ ]:
# Connetction to DataBase
conn = psycopg2.connect(host='192.168.0.103',
                        user='gpp',
                        password='gppfp2123',
                        dbname='news')

# Set User Agent
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) \
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36'}
     
# Loop Though all Pages available
for page in tqdm(range(1,2001)):

    # Set Wikipedia url to scrape the table from
    url = 'https://seekingalpha.com/market-news/' + str(page)

    # Set User Agent
#     headers = {'User-Agent': user_agents[page][0]}
    
    # Request from url
    res = requests.get(url, headers=headers)

    # Create soup object from the home page
    soup = BeautifulSoup(res.content, 'lxml')

    # Find all anchor tags with specific parameters
    table = soup.find(name="ul", attrs={'class':"item-list",'id':'latest-news-list'})
    
    # Try to Get Content
    try:
        # Loop through table rows  
        for li in table.find_all('li'):
                        
            # Link for each news page
            link = 'https://seekingalpha.com' + li.find('a').attrs['href']

            # Request from url
            res = requests.get(link, headers=headers)

            # Create soup object from the home page
            soup = BeautifulSoup(res.content, 'lxml')

            # Find all anchor tags with specific parameters
            bullets = soup.find(name='div', attrs={'id': 'bullets_ul'})

            text = ''
            for p in bullets.find_all('p'):
                if len(bullets.find_all('p')) > 1:
                    text = text + p.text
                else:
                    text = p.text
        
            with conn.cursor() as cur:

                # SQL query
                query = f"INSERT INTO seeking_alpha (id, date, header, link, content) VALUES ($${li['id']}$$, $${li['data-last-date']}$$, $${li.find('a').text}$$, $${str('https://seekingalpha.com') + li.find('a').attrs['href']}$$, $${text}$$)"

                # Execute Query
                cur.execute(query)

            # Commit to Modify the DataBase
            conn.commit()
           
            # Sleep
            time.sleep(random.randint(5,15) + np.exp(random.random()))
            time.sleep(random.randint(2,5) + np.exp(random.random()))

    # Exception Pass 
    except AttributeError:
        time.sleep(random.randint(30,45) + np.exp(random.random()))
        continue

In [ ]:
np.exp(random.random())

In [ ]:
query = """
SELECT * FROM seeking_alpha
"""

cur.execute(query)

columns = [desc[0] for desc in cur.description]
results = cur.fetchall()
pd.DataFrame(results, columns=columns)

In [ ]:
df = pd.DataFrame(results, columns=columns)

In [ ]:
df.shape